<a href="https://colab.research.google.com/github/Dexduo/Imersao-em-Ciencia-de-Dados/blob/main/Notebooks/Fatiando_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Indexação Básica e Fatiamento**

In [1]:
import numpy as np

In [2]:
array1 = np.arange(10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array1[5]

5

In [5]:
array1[6:9] #slice an array, ou seja, fatia um array, de acordo com os índices das posições passadas entre colchetes "[]"

array([6, 7, 8])

In [10]:
array1[5:8] = 12
array1

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [12]:
fatia_array = array1[5:8] #guarda a fatia na nova variável só que com ponteiros para o array original, alterar um altera o outro.
fatia_array

array([12, 12, 12])

In [14]:
fatia_array[1] = 444
array1

array([  0,   1,   2,   3,   4,  12, 444,  12,   8,   9])

**Indexação array multidimensional**

In [16]:
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(array2d[0])

print(array2d[0][1])

print(array2d[0, 1]) # essa maneira é equivalente a anterior.

[1 2 3]
2
2


### **Fatiando em dimensões maiores**

In [17]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
array2d[:2] # fatia pegando o indice 0 e indice 1 sendo o indice 2 o teto que não será incluído.

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
array2d[1, :2] # fatia pegando o elemento de indice 1 e seus valores do indice 0 e 1 sendo 2 o limitante.

array([4, 5])