<a href="https://colab.research.google.com/github/Dexduo/Imersao-em-Ciencia-de-Dados/blob/main/Notebooks/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Numpy**

In [1]:
import numpy as np

In [2]:
vetor_np = np.arange(1000000)
lista = list(range(1000000))

In [4]:
%time for _ in range(1000): vetor_np2 = vetor_np*2

CPU times: user 1.07 s, sys: 18.2 ms, total: 1.09 s
Wall time: 1.09 s


In [5]:
%time for _ in range(1000): lista2 = [x * 2 for x in lista]

CPU times: user 1min 11s, sys: 9.79 s, total: 1min 21s
Wall time: 1min 23s


In [6]:
data = np.random.randn(2, 3)

In [8]:
data * 10

array([[ 4.68143702, -9.39968651, -8.79680636],
       [13.6041721 ,  1.54444458,  2.29667566]])

In [9]:
data + data

array([[ 0.9362874 , -1.8799373 , -1.75936127],
       [ 2.72083442,  0.30888892,  0.45933513]])

### **Ndarrays**

In [11]:
dados_exemplo = [1, 8.9, 0, 3.14, 9]

numpy_array = np.array(dados_exemplo)
numpy_array

array([1.  , 8.9 , 0.  , 3.14, 9.  ])

In [14]:
dados_exemplo2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
numpy_array2 = np.array(dados_exemplo2)
dados_exemplo2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [16]:
print(numpy_array.ndim) #number of dimensions in a numpy array
print(numpy_array2.ndim)

1
2


In [17]:
print(numpy_array.shape) #dimensions of a numpy array e.g.: rows, columns etc.
print(numpy_array2.shape)

(5,)
(2, 4)


In [19]:
print(numpy_array.dtype) #shows the type of the values in the numpy array
print(numpy_array2.dtype)

float64
int64


In [21]:
array = np.array([1, 2, 3, 4])
print(array.dtype)

float_array = array.astype(np.float64) # the attribute "astype" casts the type of an numpy array to another type.
print(float_array.dtype)

int64
float64


**Other ways to create Numpy Arrays**

In [22]:
np.zeros(7) # creates a numpy array of zeros with the dimension set in parameter.

array([0., 0., 0., 0., 0., 0., 0.])

In [24]:
np.zeros((2, 7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [26]:
np.empty(10) # creates a numpy array with "empty" values with the dimension set in parameter.

array([4.74992237e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 2.32252306e-056, 4.99028112e+174, 7.73302165e-091,
       1.17714027e-047, 9.82391459e+252])

In [27]:
np.empty((2, 2, 4))

array([[[4.74992237e-310, 0.00000000e+000, 2.41907520e-312,
         2.37663529e-312],
        [2.22809558e-312, 2.46151512e-312, 6.79038654e-313,
         2.35541533e-312]],

       [[2.46151512e-312, 6.79038654e-313, 2.35541533e-312,
         6.79038654e-313],
        [2.14321575e-312, 2.22809558e-312, 2.14321575e-312,
         1.79886087e-259]]])

In [29]:
np.arange(9) # creates a numpy array with the interval set in parameter.

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

**Aritmética com Arrays Numpy**

In [32]:
array_1 = np.array(np.arange(1, 5))
array_2 = np.array([5, 6, 7, 8])

In [33]:
array_1 + array_2

array([ 6,  8, 10, 12])

In [34]:
array_1 * array_2

array([ 5, 12, 21, 32])

In [36]:
array_2 ** 2

array([25, 36, 49, 64])